// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v3.19.1
// source: demo.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "demo";

export interface HelloRequest {
  name: string;
}

export interface HelloResponse {
  message: string;
}

export interface SumRequest {
  a: number;
  b: number;
}

export interface SumResponse {
  result: number;
}

export const DEMO_PACKAGE_NAME = "demo";

export interface DemoServiceClient {
  getHello(request: HelloRequest, metadata?: Metadata): Observable<HelloResponse>;

  sum(request: SumRequest, metadata?: Metadata): Observable<SumResponse>;
}

export interface DemoServiceController {
  getHello(
    request: HelloRequest,
    metadata?: Metadata,
  ): Promise<HelloResponse> | Observable<HelloResponse> | HelloResponse;

  sum(request: SumRequest, metadata?: Metadata): Promise<SumResponse> | Observable<SumResponse> | SumResponse;
}

export function DemoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getHello", "sum"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DemoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DemoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DEMO_SERVICE_NAME = "DemoService";
